services:
  cyborgdb:
    image: cyborginc/cyborgdb-service:latest
    container_name: flux-cyborgdb
    env_file:
      - ./.env
    volumes:
      - cyborgdb-data:/home/cyborguser/.cyborgdb
      - ./logs:/app/logs
    networks:
      - internal

  postgres:
    container_name: flux-postgres
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flux -d fluxdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  md-service:
    build: ./backend/src/scripts
    container_name: flux-python-md-service
    env_file:
      - ./.env
    depends_on:
      - cyborgdb
    networks:
      - internal
    volumes:
      - uploads:/app/uploads

  backend:
    build: ./backend
    container_name: flux-backend
    ports:
      - "3008:3008"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - md-service
    networks:
      - internal
      - external
    volumes:
      - uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: flux-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  cyborgdb-data:
  postgres_data:
  uploads: